/**
 * Client-side soft-voting ensemble: Logistic Regression +
 * Histogram Gradient Boosting + MLP. All three run from the same
 * preprocessed feature vector (z-scored numeric + one-hot categorical),
 * matching what sklearn's ColumnTransformer produced at training time.
 *
 * The ensemble JSON is generated by `python ml/export_ensemble.py`.
 */

import type { PatientInput } from "./model-types";
import ensembleJson from "../../public/data/ensemble.json" with { type: "json" };

type NumericStats = { mean: number; sd: number };

type LinearModel = {
  name: "LR";
  label: string;
  category: string;
  metrics: ModelMetrics;
  numeric: Record<string, NumericStats>;
  categorical: Record<string, string[]>;
  weights: number[];
  intercept: number;
};

type Tree = {
  feature: number[];
  threshold: number[];
  left: number[];
  right: number[];
  isLeaf: boolean[];
  value: number[];
};

type HgbModel = {
  name: "HGB";
  label: string;
  category: string;
  metrics: ModelMetrics;
  init: number;
  learningRate: number;
  nTrees: number;
  trees: Tree[];
};

type MlpLayer = {
  weights: number[][];
  biases: number[];
  activation: "relu" | "logistic";
};

type MlpModel = {
  name: "MLP";
  label: string;
  category: string;
  metrics: ModelMetrics;
  layers: MlpLayer[];
};

type ModelMetrics = {
  test_auc: number;
  test_acc: number;
  brier: number;
  cv_auc_mean?: number;
  cv_auc_sd?: number;
};

type Ensemble = {
  schemaVersion: number;
  numericFeatures: string[];
  categoricalFeatures: string[];
  numeric: Record<string, NumericStats>;
  categorical: Record<string, string[]>;
  featureNames: string[];
  manuscriptThresholdCm2: number;
  ensembleMetrics: ModelMetrics;
  models: (LinearModel | HgbModel | MlpModel)[];
};

const E = ensembleJson as unknown as Ensemble;

// ---------------------------------------------------------------------------
// Preprocessing
// ---------------------------------------------------------------------------

export function computeEllipseArea(xMm: number, yMm: number): number {
  return (Math.PI * (xMm / 2) * (yMm / 2)) / 100;
}

function numericValue(input: PatientInput, feat: string): number {
  if (feat === "Tumour_Area_cm2") {
    return computeEllipseArea(input.Tumour_Size_X, input.Tumour_Size_Y);
  }
  const v = (input as unknown as Record<string, number>)[feat];
  return typeof v === "number" ? v : 0;
}

function buildDesignVector(input: PatientInput): number[] {
  const x: number[] = [];
  for (const feat of E.numericFeatures) {
    const raw = numericValue(input, feat);
    const s = E.numeric[feat];
    x.push((raw - s.mean) / (s.sd || 1));
  }
  for (const feat of E.categoricalFeatures) {
    const cats = E.categorical[feat];
    const val = String((input as unknown as Record<string, unknown>)[feat] ?? "");
    for (const cat of cats) x.push(cat === val ? 1 : 0);
  }
  return x;
}

// ---------------------------------------------------------------------------
// Per-model inference
// ---------------------------------------------------------------------------

function sigmoid(z: number): number {
  if (z >= 0) return 1 / (1 + Math.exp(-z));
  const e = Math.exp(z);
  return e / (1 + e);
}

function relu(z: number): number {
  return z > 0 ? z : 0;
}

function predictLR(model: LinearModel, x: number[]): { prob: number; logit: number } {
  let logit = model.intercept;
  for (let i = 0; i < x.length; i++) logit += model.weights[i] * x[i];
  return { prob: sigmoid(logit), logit };
}

function predictTree(tree: Tree, x: number[]): number {
  let i = 0;
  // Defensive cap on traversal depth (HGB max_depth=4 ⇒ ≤32 nodes per tree)
  for (let safety = 0; safety < 256; safety++) {
    if (tree.isLeaf[i]) return tree.value[i];
    const f = tree.feature[i];
    const t = tree.threshold[i];
    i = x[f] <= t ? tree.left[i] : tree.right[i];
  }
  return 0;
}

function predictHGB(model: HgbModel, x: number[]): { prob: number; raw: number } {
  let raw = model.init;
  for (const tree of model.trees) raw += predictTree(tree, x);
  return { prob: sigmoid(raw), raw };
}

function predictMLP(model: MlpModel, x: number[]): { prob: number } {
  let activations = x;
  for (const layer of model.layers) {
    const out = new Array(layer.biases.length);
    for (let j = 0; j < layer.biases.length; j++) {
      let z = layer.biases[j];
      const col = layer.weights;
      for (let i = 0; i < activations.length; i++) z += activations[i] * col[i][j];
      out[j] = layer.activation === "relu" ? relu(z) : sigmoid(z);
    }
    activations = out;
  }
  return { prob: activations[0] };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export type ModelPrediction = {
  name: "LR" | "HGB" | "MLP";
  label: string;
  category: string;
  probability: number;
  metrics: ModelMetrics;
};

export type EnsemblePrediction = {
  /** Probability of ≥13 sections — soft-vote average of the 3 models */
  probability: number;
  /** Distance to the 0.5 decision boundary */
  distanceToBoundary: number;
  /** "high" if every model agrees on the side AND their range is narrow */
  confidence: "high" | "borderline" | "split";
  /** Range of probabilities across the ensemble — narrower = more agreement */
  spread: number;
  label: "≥13 sections likely" | "<13 sections likely";
  tumourAreaCm2: number;
  exceedsThreshold: boolean;
  mbs: { code: "31000" | "31001" | "31002"; label: string; scheduleFee: number };
  /** Per-model probabilities so the UI can show the breakdown */
  perModel: ModelPrediction[];
  /** Top per-feature contributions from the LR model (signed logit pull) */
  factors: PredictionFactor[];
};

export type PredictionFactor = {
  feature: string;
  label: string;
  kind: "numeric" | "categorical";
  value: number | string;
  cohortMean?: number;
  z?: number;
  contribution: number;
  direction: "up" | "down" | "flat";
};

const FEATURE_LABELS: Record<string, string> = {
  Age: "Patient age",
  Tumour_Size_X: "Tumour width",
  Tumour_Size_Y: "Tumour height",
  Tumour_Area_cm2: "Tumour area (ellipse)",
  Sex: "Sex",
  See_Do: "See-and-do planning",
  Experience: "Surgeon experience",
  Recurrent: "Recurrent tumour",
  Tumour_Stats: "Tumour type",
  Body_Site: "Body site",
  Body_Zone: "Body zone",
  Laterality: "Laterality",
  Unit: "Anatomical unit",
  Aggressive_Histopathology: "Aggressive histopathology",
  Biopsy: "Biopsy method",
  Smoking: "Smoking",
};

function mbsBucket(prob: number): EnsemblePrediction["mbs"] {
  if (prob >= 0.5) return { code: "31002", label: "Mohs ≥13 sections", scheduleFee: 1016.4 };
  if (prob >= 0.25) return { code: "31001", label: "Mohs 7–12 sections", scheduleFee: 847.0 };
  return { code: "31000", label: "Mohs 1–6 sections", scheduleFee: 677.7 };
}

export function predict(input: PatientInput): EnsemblePrediction {
  const x = buildDesignVector(input);
  const lr = E.models.find((m) => m.name === "LR") as LinearModel;
  const hgb = E.models.find((m) => m.name === "HGB") as HgbModel;
  const mlp = E.models.find((m) => m.name === "MLP") as MlpModel;

  const lrOut = predictLR(lr, x);
  const hgbOut = predictHGB(hgb, x);
  const mlpOut = predictMLP(mlp, x);

  const probs = [lrOut.prob, hgbOut.prob, mlpOut.prob];
  const probability = (probs[0] + probs[1] + probs[2]) / 3;
  const spread = Math.max(...probs) - Math.min(...probs);
  const allAgree = probs.every((p) => (p >= 0.5) === (probability >= 0.5));
  const distanceToBoundary = Math.abs(probability - 0.5);
  let confidence: EnsemblePrediction["confidence"];
  if (!allAgree) confidence = "split";
  else if (distanceToBoundary >= 0.15) confidence = "high";
  else confidence = "borderline";

  const tumourAreaCm2 = computeEllipseArea(input.Tumour_Size_X, input.Tumour_Size_Y);

  // Per-feature contribution from the LR model — signed logit pull
  const numericCount = E.numericFeatures.length;
  const factors: PredictionFactor[] = [];
  for (let i = 0; i < numericCount; i++) {
    const feat = E.numericFeatures[i];
    const z = x[i];
    const contribution = lr.weights[i] * z;
    const val = numericValue(input, feat);
    factors.push({
      feature: feat,
      label: FEATURE_LABELS[feat] ?? feat,
      kind: "numeric",
      value: val,
      cohortMean: E.numeric[feat].mean,
      z: Number(z.toFixed(3)),
      contribution: Number(contribution.toFixed(4)),
      direction: contribution > 0.02 ? "up" : contribution < -0.02 ? "down" : "flat",
    });
  }
  let col = numericCount;
  for (const feat of E.categoricalFeatures) {
    const cats = E.categorical[feat];
    const val = String((input as unknown as Record<string, unknown>)[feat] ?? "");
    const activeIdx = cats.indexOf(val);
    const contribution = activeIdx >= 0 ? lr.weights[col + activeIdx] : 0;
    factors.push({
      feature: feat,
      label: FEATURE_LABELS[feat] ?? feat,
      kind: "categorical",
      value: val,
      contribution: Number(contribution.toFixed(4)),
      direction: contribution > 0.05 ? "up" : contribution < -0.05 ? "down" : "flat",
    });
    col += cats.length;
  }
  factors.sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution));

  return {
    probability: Number(probability.toFixed(4)),
    distanceToBoundary: Number(distanceToBoundary.toFixed(4)),
    confidence,
    spread: Number(spread.toFixed(4)),
    label: probability >= 0.5 ? "≥13 sections likely" : "<13 sections likely",
    tumourAreaCm2: Number(tumourAreaCm2.toFixed(3)),
    exceedsThreshold: tumourAreaCm2 >= E.manuscriptThresholdCm2,
    mbs: mbsBucket(probability),
    perModel: [
      { name: "LR", label: lr.label, category: lr.category, probability: Number(lrOut.prob.toFixed(4)), metrics: lr.metrics },
      { name: "HGB", label: hgb.label, category: hgb.category, probability: Number(hgbOut.prob.toFixed(4)), metrics: hgb.metrics },
      { name: "MLP", label: mlp.label, category: mlp.category, probability: Number(mlpOut.prob.toFixed(4)), metrics: mlp.metrics },
    ],
    factors,
  };
}

export const ensembleMeta = {
  ensembleMetrics: E.ensembleMetrics,
  numericFeatures: E.numericFeatures,
  categoricalFeatures: E.categoricalFeatures,
  categorical: E.categorical,
  featureLabels: FEATURE_LABELS,
  manuscriptThresholdCm2: E.manuscriptThresholdCm2,
  perModelMetrics: E.models.map((m) => ({
    name: m.name,
    label: m.label,
    category: m.category,
    metrics: m.metrics,
  })),
};
